### ISSUE TITLE
How to do transaction without have to write it in Lua?

### ISSUE THREAD

**Issue by kokizzu** [tarantool/go-tarantool#101]
https://www.tarantool.io/en/doc/latest/book/box/atomic/

**Comment by funny-falcon** [comment]
Afaik there is no way for external transaction.

**Comment by Totktonada** [comment]
Now we have the interactive transactions support on the server side: https://github.com/tarantool/tarantool/issues/2016. So it worth to implement in the connector.

A brief protocol description is here: https://github.com/tarantool/doc/issues/2310.

net.box API as a reference: https://github.com/tarantool/doc/issues/2311.

**Comment by AnaNek** [comment]
The proposed API for this feature is the following:

1. Add method to create a stream object for `Connection` and `ConnectionPool`, method for `Connection` doesn't get any parameters, method for `ConnectionPool` get `mode` parameter.

```golang
func (conn *Connection) NewStream() (*Stream, error);
func (connPool *ConnectionPool) NewStream(userMode Mode) (*Stream, error);
```

2. Implement `Stream` object with the same methods as for `Connection` and add `Begin()`, `Commit()`, `Rollback()` methods.
`Begin()` -  start transaction via iproto stream.
`Commit()` - commit transaction.
`Rollback()` - rollback transaction.

Use case example:

```golang
package main

import (
        "fmt"
        "log"

        "github.com/tarantool/go-tarantool"
)

func main() {
        conn, err := Connect(server, opts)
        if err != nil {
	    fmt.Printf("Failed to connect: %s", err.Error())
            return
        }
        if conn == nil {
	    fmt.Printf("conn is nil after Connect")
            return
        }
        defer conn.Close()

        stream, err := conn.NewStream()
        if err != nil {
	    fmt.Printf("Failed to create stream: %s", err.Error())
            return
        }
        if stream == nil {
	    fmt.Printf("stream is nil after NewStream")
            return
        }

        stream.Begin()

        stream.Insert("test", &Tuple{Id: 32, Msg: "test", Name: "one"})
        stream.Insert("test", &Tuple{Id: 2, Msg: "test", Name: "two"})
        stream.Insert("test", &Tuple{Id: 11, Msg: "test", Name: "three"})

        stream.Commit()
}

```
