### ISSUE TITLE
Test fails with Tarantool 2.8.1 or newer

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/go-tarantool#105]
[This commit](https://github.com/tarantool/tarantool/commit/d11fb3061e15faf4e0eb5375fb8056b4e64348ae) has changes duplicate key message in Tarantool 2.8.1. Thus test run fails in `Example()` test of [example_test.go](https://github.com/tarantool/go-tarantool/blob/56fe55c5fa5c760212e6266af373ea59cd181bb7/example_test.go) file since Tarantool returns
```
Insert Error Duplicate key exists in unique index "primary" in space "test" with old tuple - [10, "test", "one"] and new tuple - [10, "test", "one"] (0x3)
```
while
https://github.com/tarantool/go-tarantool/blob/56fe55c5fa5c760212e6266af373ea59cd181bb7/example_test.go#L197
is expected.

To fix tests for Tarantool 2.x (since versions prior to 2.8.2 is EOL or will be there soon), [example_test.go](https://github.com/tarantool/go-tarantool/blob/56fe55c5fa5c760212e6266af373ea59cd181bb7/example_test.go) should be rewritten with some kind of fork based on Tarantool version or test case comparison should be replaced with regex.

**Comment by funny-falcon** [comment]
It seems there were copy-paste error from the beginning (11 != 10):
```
	// insert new tuple { 11, 1 }
	resp, err = client.Insert("test", &Tuple{Id: 10, Msg: "test", Name: "one"})
```
Or there should be two inserts: with error on duplicate and new one.

There is no need too make "fork". Just change `fmt.Println("Insert Error", err)` to something more clever.

**Comment by ylobankov** [comment]
This bug blocks resolving the issue https://github.com/tarantool/tarantool/issues/6607. So we need to fix it ASAP.
