### ISSUE TITLE
Update link to "Connectors" chapter in README

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/go-tarantool#109]
AFAIU the link must point to https://www.tarantool.io/en/doc/latest/getting_started/getting_started_go/

**Comment by AnaNek** [comment]
I suppose it is closed by f297cfed2a03b0842c89947cc781204760782a1c

**Comment by Totktonada** [comment]
Seems so. Thanks!

Duplicate of #130, closed in PR #131.
