### ISSUE TITLE
How to use eval with custom args

### ISSUE THREAD

**Issue by alexeyknyshev** [tarantool/go-tarantool#11]
For example, I have this lua script for determining name of box.space by id:

tnt.Eval("box.space." + spaceIdStr + ".name", []interface{}{})

It seems to be ugly and error prone way. So how can I pass some data to lua and how to use this data as lua varable(s)?

**Comment by mialinx** [comment]
1) define stored lua procedure  in your init.lua  (or another lua module) loaded in tarantool.
For instance
```
function name2id(name)
   local id = 42
   return id  // result is scalar value here
end
```

2) use Call to get the result
```
resp, err := connection.Call("name2id", []interface{}{ "users" })
if err != nil {
  return err
}
uid := resp.Data[0].([]interface{})[0].(uint64)    // Data is table of 1 tuple of 1 element here
```

**Comment by alexeyknyshev** [comment]
Thx a lot

**Comment by savinov** [comment]
TarantoolConnection16Base has this method to execute LUA eval: eval(String expression, Object... args)

But how to access to args in LUA?
