### ISSUE TITLE
Support datetime

### ISSUE THREAD

**Issue by Totktonada** [tarantool/go-tarantool#118]
It is not offered ATM (2021-12-13), but AFAIK there is agreement on the representation in msgpack. See https://github.com/tarantool/tarantool/pull/6660.

**Comment by ligurio** [comment]
Similar PR with UUID support - https://github.com/tarantool/go-tarantool/pull/104

**Comment by ligurio** [comment]
- Datetime storage schema https://github.com/tarantool/tarantool/discussions/6244#discussioncomment-1043990
- box, datetime: messagepack serialization - step.4 https://github.com/tarantool/tarantool/pull/6660
