### ISSUE TITLE
Setup a release process

### ISSUE THREAD

**Issue by Totktonada** [tarantool/go-tarantool#121]
- Add CHANGELOG.md[^1].
- Whether we need to deploy the connector to pkg.go.dev[^2]?
- Start to tag releases and write release notes (within annotated tag and in release notes)[^3].
- Describe release process in a wiki.

Anything else? Thoughts?

Initially requested in https://github.com/tarantool/go-tarantool/issues/65#issuecomment-406503830, but I added my thoughts here.

[^1]: I hope, we'll NOT strictly follow the 'keep a changelog; format. It is better to adopt it to be maximal expressive. Choose the best categories, add an overview section and so on.
[^2]: I'm not a Go developer, so it is terra ingognita for me. Need to investigate the topic.
[^3]: I hope the release notes will be just copy of the relevant section from the changelog. There is no need to support two representations of the same idea: offer a user information about changes in the easy to understand form (without gory details).

**Comment by ligurio** [comment]
> Describe release process in a wiki.

https://github.com/tarantool/go-tarantool/wiki/How-to-release
