### ISSUE TITLE
Is Connection thread safe

### ISSUE THREAD

**Issue by alexeyknyshev** [tarantool/go-tarantool#13]
Can I use tarantool.Connection from multiply goroutenes without sync?
Is there any API such as in Redis connector radix (https://godoc.org/github.com/mediocregopher/radix.v2/pool)?

**Comment by mialinx** [comment]
Yes, you can. tarantool.Connection is thread-safe.

You don't need a connection pool normally, as tarantool serves multiple simultaneous requests with one connection. We used connection pool, and it gave us only 10% performance boost.

**Comment by alexeyknyshev** [comment]
Thanks

Regards, Alexey Knyshev

**Comment by mialinx** [comment]
If
