### ISSUE TITLE
Non-obvious behaviour: bug or feaеure?

### ISSUE THREAD

**Issue by shilkin** [tarantool/go-tarantool#14]
connection.go: 193
In case of conn.dial() return error and
if conn.opts.Reconnect > 0 but conn.opts.MaxReconnects == 0
we'll stuck in reconnection loop anyway.

Look, when I set MaxReconnects to 0, I want to say: "I don't want to reconnect, go-tarantool",
but go-tarantool start trying to reconnect.

**Comment by mialinx** [comment]
It's a feature. I fixed documentation to make it clear.

If you want to disable automatic reconnect, set Reconnect = 0
