### ISSUE TITLE
Run tests on macOS

### ISSUE THREAD

**Issue by ligurio** [tarantool/go-tarantool#157]
For declaring macOS support, we need to run tests on macOS. In this issue, we need to extend test environments in Github Actions with macOS.

Don't forget to add macOS as supported platform in th README.

**Comment by Totktonada** [comment]
Consider an [example](https://github.com/tarantool/smtp/blob/29dd5812afa947833348674ef34cec80ae3099be/.github/workflows/testing.yml#L134-L302) of such CI job in the tarantool/smtp module. I guess we can just copy-paste it and adjust a bit.
