### ISSUE TITLE
v2: update public API

### ISSUE THREAD

**Issue by ligurio** [tarantool/go-tarantool#158]
Unlike other program languages like Java and Python that use access modifiers such as public, private, or protected to specify scope, Go determines if an item is exported and unexported through how it is declared. Exporting an item in this case makes it visible outside the current package. If it’s not exported, it is only visible and usable from within the package it was defined. This external visibility is controlled by capitalizing the first letter of the item declared. All declarations, such as Types, Variables, Constants, Functions, etc., that start with a capital letter are visible outside the current package.

There are many things in go-connector that exposed as a part of public API. We need to update a public API and probably make some of these things invisible for external users.

We need to document this if we want to keep these things in a public API.

**NOTE**: It is a breaking change and next release with these changes should bump a MAJOR version.

- constants declared in `const.go`, https://github.com/tarantool/go-tarantool/blob/31ebde8f41b3caef17a44b51d69db19661d1b82d/const.go#L4-L31
- constants declared in `consts.go`, https://github.com/tarantool/go-tarantool/blob/2c3af56968b70eb0645d9f15809876e01fbf30ed/const.go#L17-L31
- constants declared in `consts.go`, https://github.com/tarantool/go-tarantool/blob/2c3af56968b70eb0645d9f15809876e01fbf30ed/const.go#L46-L51
- Connector interface in `connector.go`, https://github.com/tarantool/go-tarantool/blob/31ebde8f41b3caef17a44b51d69db19661d1b82d/connector.go#L5-L40
- Deadline methods, https://github.com/tarantool/go-tarantool/blob/31ebde8f41b3caef17a44b51d69db19661d1b82d/deadline_io.go#L8-L27
- UUID ext type constant https://github.com/tarantool/go-tarantool/blob/2c3af56968b70eb0645d9f15809876e01fbf30ed/uuid/uuid.go#L15
- smallbuf api, https://github.com/tarantool/go-tarantool/blob/7897bafc1b6b8a292afb33e57a813791e46bf613/smallbuf.go#L13-L97

**Comment by oleg-jukovec** [comment]
+ `RoundRobinStrategy`

https://github.com/tarantool/go-tarantool/blob/d6d0031d7a0ce9959edf57f9407bba9652a37506/connection_pool/round_robin.go
