### ISSUE TITLE
something wrong?

### ISSUE THREAD

**Issue by monopollly** [tarantool/go-tarantool#17]
go client is not stable?

[bug screenshot](https://gyazo.com/a8b3bde63e44de0758852139992fb33d)

      //tarantool
	server := ":3301"
	opts := tarantool.Opts{
        Timeout:       500 * time.Millisecond,
        Reconnect:     1 * time.Second,
        MaxReconnects: 3,
        User:          "test",
        Pass:          "test",
    }
	client, err := tarantool.Connect(server, opts)
    if err != nil {
        ff("Failed to connect: ", err.Error())
    }
	resp, err := client.Ping()
    ff(resp.Code)
    ff(resp.Data)
    ff(err)

> Failed to connect:  client connection is not ready
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x16dd42]
 

> goroutine 1 [running]:
> panic(0x766de0, 0xc82000a120)
>         /usr/local/go/src/runtime/panic.go:464 +0x3e6
> github.com/tarantool/go-tarantool.(*Connection).nextRequestId(0x0, 0xc82025f800)

**Comment by mialinx** [comment]
You got error:   "Failed to connect: client connection is not ready".
client variable is nil. Thus, you should not use this connection.

BTW, Reconnect options restores connection automatically, but only if connection have been initially established. Is it expected behavior for you?

**Comment by monopollly** [comment]
No, you can't use `return` in main()
Now its ok I think the problem was in ":3301"
I changed to `server := "127.0.0.1:3301"` and oh magic its works!

**Comment by mialinx** [comment]
Anyway, you should not use client if Connect call returns error.
