### ISSUE TITLE
Add missing and new queue methods

### ISSUE THREAD

**Issue by 0x501D** [tarantool/go-tarantool#177]
Currently, go-tarantool does not support the following methods:

Old:

* [identify()](https://github.com/tarantool/queue#session-identify)
* [touch()](https://github.com/tarantool/queue#increasing-ttr-andor-ttl-for-tasks)

New:

* [release_all()](https://github.com/tarantool/queue#releasing-all-taken-tasks)
* [state()](https://github.com/tarantool/queue#queue-state-diagram)

**Comment by oleg-jukovec** [comment]
https://github.com/tarantool/go-tarantool/issues/110
