### ISSUE TITLE
result as interface{}

### ISSUE THREAD

**Issue by monopollly** [tarantool/go-tarantool#18]
So, I got a response from tarantool as json in interface{} container
and how Unmarshal it? how work with it (cause it can be a variable structure)? 
give me an advice please...

**Comment by funny-falcon** [comment]
Did you use dynamically typed languages before? If so, then you already know.

Any way, learn a bit more Go, please.

**Comment by funny-falcon** [comment]
Cause your question is not related to tarantool driver.

You nay ask the same question: "i have a Json of unknown shape, and json unpacker returns me interface{} , how I will deal with?"

It is exactly sane question, and you should find answer in other places (read the docs).

**Comment by mialinx** [comment]
For easy debugging you can also do
```go
resp, err := tarantool.Select()
tuple := resp.Data[0].([]interface{})
fmt.Printf("%#v\n",  tuple)
```
You will know actual structure.
Than you can do type assertion to get fields
```go
id := tuple[0].(uint64)
name := tuple[1].(string)
var members []unint64
if len(tuple) > 2 {
    for i, m := range  tuple[2].([]interface{}) {
        members = append(members, m.(uint64))
    }
}
```
