### ISSUE TITLE
The padding in a connection shard structure

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/go-tarantool#197]
There is a 128-byte padding in a connection shard structure and there is no any obvious reason for it.
https://github.com/tarantool/go-tarantool/blob/e1bb59cf1c8c90df14197d0974a6178a66d46b84/connection.go#L155

```go
type ConnShard1 struct {
	rmut     sync.Mutex
	requests [requestsMap]futureList
	bufmut   sync.Mutex
	buf      smallWBuf
	enc      *msgpack.Encoder
	_pad     [16]uint64 //nolint: unused,structcheck
}

type ConnShard2 struct {
	rmut            sync.Mutex
	requests        [requestsMap]futureList
	requestsWithCtx [requestsMap]futureList
	bufmut          sync.Mutex
	buf             smallWBuf
	enc             *msgpack.Encoder
	_pad            [16]uint64 //nolint: unused,structcheck
}

func TestConnShard(t *testing.T) {
	v := ConnShard1{}
	typ := reflect.TypeOf(v)
	fmt.Printf("Type ConnShard1 is %d bytes long\n", typ.Size())
	n := typ.NumField()
	for i := 0; i < n; i++ {
		field := typ.Field(i)
		fmt.Printf("%s at offset %v, size=%d, align=%d\n",
			field.Name, field.Offset, field.Type.Size(),
			field.Type.Align())
	}
	fmt.Printf("ConnShard1 align is %d\n\n\n", typ.Align())

	v2 := ConnShard2{}
	typ2 := reflect.TypeOf(v2)
	fmt.Printf("Type ConnShard2 is %d bytes long\n", typ2.Size())
	n = typ.NumField()
	for i := 0; i < n; i++ {
		field := typ2.Field(i)
		fmt.Printf("%s at offset %v, size=%d, align=%d\n",
			field.Name, field.Offset, field.Type.Size(),
			field.Type.Align())
	}
	fmt.Printf("ConnShard2 align is %d\n", typ2.Align())
}
```

The output:

```
Type ConnShard1 is 2240 bytes long
rmut at offset 0, size=8, align=4
requests at offset 8, size=2048, align=8
bufmut at offset 2056, size=8, align=4
buf at offset 2064, size=40, align=8
enc at offset 2104, size=8, align=8
_pad at offset 2112, size=128, align=8
ConnShard1 align is 8


Type ConnShard2 is 4288 bytes long
rmut at offset 0, size=8, align=4
requests at offset 8, size=2048, align=8
requestsWithCtx at offset 2056, size=2048, align=8
bufmut at offset 4104, size=8, align=4
buf at offset 4112, size=40, align=8
enc at offset 4152, size=8, align=8
_pad at offset 4160, size=128, align=8
ConnShard2 align is 8
```

_Originally posted by @vr009 in https://github.com/tarantool/go-tarantool/pull/173#discussion_r927435973_

**Comment by oleg-jukovec** [comment]
https://github.com/tarantool/go-tarantool/commit/f62aac9c3510e87865329891813ee602fc366e93

**Comment by vr009** [comment]
I haven't read yet, but FYI https://dave.cheney.net/2015/10/09/padding-is-hard.

**Comment by oleg-jukovec** [comment]
> I haven't read yet, but FYI https://dave.cheney.net/2015/10/09/padding-is-hard. @DifferentialOrange @oleg-jukovec

It doesn't look like our case at first glance.

> I have also heard, that there is a practice in C, to add some byte field after some pointer in the structure and this field is needed for allocation a memory for this pointer, something like that.

You can dig deeper and to google something like: "C struct padding CPU cacheline", "C struct padding cache miss". I can't remember a good article right now, but something like this may help:

https://medium.com/software-design/why-software-developers-should-care-about-cpu-caches-8da04355bb8a
http://psy-lob-saw.blogspot.com/2014/06/notes-on-false-sharing.html

I assume that the optimization in this case was to avoid intersection of a cache line by nearby connShards inside the array [shards]connShard . As an example, if a thread modifies a field of connShard[X] it should not affect to an another thread that works with a field on connShard[X+1].

This is just a guess, I don't see the point now to find out exactly the reason. It was broken for a long time
