### ISSUE TITLE
Reconnect options, working?

### ISSUE THREAD

**Issue by kmansoft** [tarantool/go-tarantool#20]
Not sure if this is a bug or my misunderstanding...

I'm running a test app with these options, artificial values to make the point:

```go
    opts := tarantool.Opts{
		Timeout:       500 * time.Millisecond,
		Reconnect:     100 * time.Second,
		MaxReconnects: 300000,
    }
```

If I shutdown or SIGKILL the tarantool side of things, and quickly restart (within maybe 1 second, the time it takes me to "arrow up" + "enter") -- then I expect the client to reconnect and keep going.

Instead, my client gets an error from the Tarantool bindings, like this:

```
		_, err := client.Call("push_ChangeSub", []interface{}{sub_id, dev_id, now})
		if err != nil {
			log.Fatalf("Error calling function: %s", err.Error())
		}
```
Actual message, happens immediately after I shutdown / kill tarantool:
```
Error calling function: EOF
```

Am I misunderstanding what the reconnect options do?

Is there good way to add basic fault tolerance / reconnect?

Should I be calling client.Ping() before every request (seems expensive)?

**Comment by mialinx** [comment]
Could you provide a complete programm ?

**Comment by mialinx** [comment]
And, by the way, automatic reconnect does not imply automatic rerunning queries.
When tarantool is down your program WILL get errors such as EOF.

**Comment by kmansoft** [comment]
Sure: https://gist.github.com/kmansoft/7081be8dbab98de2c2afea6accb35604

> automatic reconnect does not imply automatic rerunning queries

OK, so what is supposed to happen? How does this work?

Will the "current" request return an error code, but the "next one" on same client connection object is supposed to try and reconnect? Is that how it's supposed to work?

I'd like to be able to restart the Tarantool side of things if needed, and have the client have some degree of tolerance to this. Is there a good way to do it?

**Comment by kmansoft** [comment]
And this my lua script: https://gist.github.com/kmansoft/48bbb1fd933f5779b1e51052d145ad4e

**Comment by mialinx** [comment]
It supposed to reestablish connection after tarantool restarts.
You don't need to connect manually (eg. call tarantool.Connect) each time.
But all request issued during tarantool restart will be failed, because restart may take minutes and we can't queue them inside the driver.

You have two options:
* just log an error and continue running (use log.Printf instead of log.Fatalf)
* try to defer failed request and run them later

**Comment by kmansoft** [comment]
OK, tried with a non-fatal message, observations:

- The operation returns io.EOF, seems like only once (correct?)
- The driver tries to reconnect, good
- Meanwhile, any operations while this is happening return "client connection not ready":

https://github.com/tarantool/go-tarantool/blob/master/request.go#L286

- If I restart tarantool fast enough, the driver does reconnect, and the app continues. Also good.

Some issues however:

- No proper error code for the "client connection is not ready" state.

I can check for io.EOF but it only happens once on the first request when the connection has gone missing.

- If I don't restart tarantool fast enough, the connection says "giving up" and the error remains "client connection not ready".

And therefore, it does not seem possible in app side logic to know if: 1) the driver is still trying to reconnect, and so the app can retry the operation or 2) the driver has given up, the app should try to establish a new connection.

- Would like to see a proper error code for "driver gave up trying to reconnect".

Guess I could set MaxReconnects to some very large number, but that seems dirty.

And taking a broader view: have you thought about implementing some sort of "retry handler" (retry policy) at the driver level?

I understand that it's not possible to buffer an arbitrary large number of requests in the driver, but having a way to retry just one seems useful (optionally, if the app code sets the right options).

Something similar to this?

https://hc.apache.org/httpcomponents-client-ga/tutorial/html/fundamentals.html#d5e316

**Comment by mialinx** [comment]
I don't guarantee any particular kind of error, during restart. You may get io.EOF or any other underlying network/io error.

We may create special type for client side errors and add client error codes, so you could distinguish them from server and network problems. We also can return specific error code to inform you MaxReconnects limit reached.  Will it work for you ? 


`Guess I could set MaxReconnects to some very large number, but that seems dirty.`
`2) the driver has given up, the app should try to establish a new connection.`

What's the difference ? You are either trying to reconnect or giving it up. The same behavior can be expressed using MaxReconnects. I don't see reason to support custom reconnect policies at the moment...

**Comment by kmansoft** [comment]
> What's the difference ? You are either trying to reconnect or giving it up.

The client would know if it needs to abandon the current connection object (if it reached the MaxReconnects limit and won't try to connect anymore) or create a new one which would (try to connect).

No guarantees of whether _that_ would help -- if tarantool is still down -- but if tarantool is up now, then the app will be able to start working again.

> I don't guarantee any particular kind of error, during restart. You may get io.EOF or any other underlying network/io error.

You get io.EOF right now once, OK, you're saying it could be some other network error, fine, I see that.

What happens next, while the client keep trying to reconnect is the bigger issue to me. Right now it just does an errors.New with a hardcoded string, not easy to check.

**Comment by mialinx** [comment]
`No guarantees of whether that would help -- if tarantool is still down`
If tarantool is still down Connect call will fail with an error.
Reconnect logic only works after successful initial connect.

**Comment by kmansoft** [comment]
> Reconnect logic only works after successful initial connect.

Yes of course, but if tarantool is back up and the connection has reached MaxReconnects -- then *unless* the application abandons this connection and creates a new one, it will keep failing forever.

And right now it does not seem possible to catch this case, to differentiate between:

- "tarantool is still down and connection has not reached MaxReconnects and will keep trying"

vs.

- "tarantool is back up, but the connection has reached MaxReconnects and will not keep trying".

**Comment by mialinx** [comment]
Special type ClientError added in 89bf02b938637d8c3369ab79dfb07f2a3796a073

Now, you can distinguish client side errors

```go
package main

import (
	"fmt"
	"github.com/tarantool/go-tarantool"
	"time"
)

var server = "127.0.0.1:3013"
var spaceNo = uint32(512)
var spaceName = "test"
var indexNo = uint32(0)
var indexName = "primary"
var opts = tarantool.Opts{
	Timeout:       100 * time.Millisecond,
	Reconnect:     500 * time.Millisecond,
	MaxReconnects: 10,
	User:          "test",
	Pass:          "test",
}

func main() {
	conn, err := tarantool.Connect(server, opts)
	if err != nil {
		fmt.Printf("Failed to connect: %s\n", err.Error())
		return
	}

	for {
		_, err := conn.Ping()
		if err != nil {
			fmt.Printf("Failed to Ping: %s\n", err.Error())
			if err, ok := err.(tarantool.ClientError); ok && !err.Temporary() {
				return
			}
		} else {
			fmt.Printf("Ping\n")
		}
		time.Sleep(time.Second)
	}
}

```

**Comment by kmansoft** [comment]
Thanks I'll give it a try
