### ISSUE TITLE
Add replication support

### ISSUE THREAD

**Issue by BokarevNik** [tarantool/go-tarantool#203]
Another connector (https://github.com/viciious/go-tarantool) supports subscribing to replicaset like regular replica (https://github.com/viciious/go-tarantool/blob/master/slave.go) and anonymous replica (https://github.com/viciious/go-tarantool/blob/master/anon_slave.go). It will be great to implement  features like that in this connector.

**Comment by Totktonada** [comment]
Why don't just use Victor's connector for those purposes?

**Comment by hackallcode** [comment]
There are bugs in that library, it doesn't support decimal and uuid and it needs to be fixed.

We can fix a 3rd party library, but would like to use the original one and spend time on it, not on a third-party.

**Comment by viciious** [comment]
> There are bugs in that library

What bugs exactly?

**Comment by LeonidVas** [comment]
Bosses say that such functionality is planned only in the EE versions of the products.
