### ISSUE TITLE
Support graceful shutdown

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/go-tarantool#214]
The graceful shutdown protocol is a mechanism that helps to prevent data loss in requests in case of a shutdown command.

https://www.tarantool.io/en/doc/latest/dev_guide/internals/box_protocol/#graceful-shutdown-protocol

**Comment by R-omk** [comment]
https://github.com/tarantool/go-tarantool/issues/119 this should be implemented first.

Details https://github.com/tarantool/doc/issues/2633

**Comment by ice-ares** [comment]
what about supporting graceful shutdown from the client? Especially in the connection pool. I.E. client called .Close() or context cancelled, but we still have pending requests

**Comment by ice-ares** [comment]
> what about supporting graceful shutdown from the client? Especially in the connection pool. I.E. client called .Close() or context cancelled, but we still have pending requests

@oleg-jukovec what about that?

**Comment by oleg-jukovec** [comment]
>  What about supporting graceful shutdown from the client?

Unfortunately, this is not in the product plan. First of all, because the request counter can be implemented on the client side.

> Especially in the connection pool. I.E. client called .Close()

I have opened a new issue:
https://github.com/tarantool/go-tarantool/issues/257

> or context cancelled

This is a limitation of the IPHOTO protocol. We cannot cancel a request that has already been sent over network.
Therefore, if the request has already been sent, it is canceled only at the Go-language level.
