### ISSUE TITLE
DATA RACE

### ISSUE THREAD

**Issue by awekening2** [tarantool/go-tarantool#218]
go: 1.19
tarantool: 1.10 / 2.10

Все запускается из докера
Использую базовый образ для приложения  [(acim/go-reflex)](https://hub.docker.com/r/acim/go-reflex)
При запуске приложения получаем WARNING: DATA RACE
Пример приложения(warning)  и лог:
[warning.zip](https://github.com/tarantool/go-tarantool/files/9616672/warning.zip)
[tnt.log](https://github.com/tarantool/go-tarantool/files/9616676/tnt.log)

**Comment by oleg-jukovec** [comment]
Thank you for the issue!

It does not look like a critical problem. The data race should not cause a problem because the ping request does not use schema.

But in any case, we will try to fix it.
