### ISSUE TITLE
UpsertTyped possibly(?) meaningless

### ISSUE THREAD

**Issue by kmansoft** [tarantool/go-tarantool#23]
Hi,

I see you've completed adding *Typed variations of several data manipulation methods.

One of those new methods is UpsertTyped.

However, per the docs here:

https://tarantool.org/doc/book/box/box_space.html#box-space-upsert

box.space.upsert() always returns nil

Given this, having an UpsertTyped is possibly

1) meaningless (res will always remain "nil") and

2) misleading (a developer who hasn't read the tarantool docs, only go-tarantool docs, might assume that Upsert is supposed to return the just inserted tuple)

**Comment by mialinx** [comment]
Typed suffix means typed deserialization, the way msgpack decodes a stream into the passed interface.
Typically structure is a list of tuples, but in general an arbitrary structure may be returned.
You need to consult to tarantool docs about data structure any particular method may return.

**Comment by kmansoft** [comment]
> Typed suffix means typed deserialization, the way msgpack decodes a stream into the passed interface.

Yes, I understand what the suffix means and have consulted Tarantool docs:

https://tarantool.org/doc/book/box/box_space.html#box-space-upsert

> However, **unlike insert or update, upsert will not read a tuple** and perform error checks before returning -- **this is a design feature** which enhances throughput but requires more caution on the part of the user.

> Return: null

In other words:

Tarantool's "upsert" operation, by design, always returns "nil".

Never returns a tuple.

There is nothing to decode and nothing to return, "res" will always remain "nil".

But having UpsertTyped method _makes it seem_ that upsert returns _something_ which it does not.

Confusing. Misleading.
