### ISSUE TITLE
golint does not print backtrace

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/go-tarantool#231]
It is a pain to debug errors like
```
  Error: S1002: should omit comparison to bool constant, can be simplified to `connected` (gosimple)
  Error: SA5001: should check returned error before deferring conn.Close() (staticcheck)
  Error: SA5001: should check returned error before deferring conn.Close() (staticcheck)
```
without having any information about what file and line they are referred to.

**Comment by oleg-jukovec** [comment]
Yes, we need to fix it on CI, but on the local machine you could to use the make target:

```
$ make golangci-lint 
golangci-lint run -E goimports -D errcheck
connection_pool/connection_pool.go:46:19: undeclared name: `tarantool` (typecheck)
	Discovered(conn *tarantool.Connection, role Role) error
```

**Comment by DifferentialOrange** [comment]
> Yes, we need to fix it on CI ( [golangci/golangci-lint-action#119](https://github.com/golangci/golangci-lint-action/issues/119) , [tarantool/tt#116](https://github.com/tarantool/tt/pull/116) ), but on the local machine you could to use the make target:
> 
> ```
> $ make golangci-lint 
> golangci-lint run -E goimports -D errcheck
> connection_pool/connection_pool.go:46:19: undeclared name: `tarantool` (typecheck)
> 	Discovered(conn *tarantool.Connection, role Role) error
> ```

Either something had changed between versions or flags are different from the CI ones.

![image](https://user-images.githubusercontent.com/20455996/204274633-0e2cbb47-9fe9-4d05-9597-e432de1cfc53.png)

**Comment by DifferentialOrange** [comment]
> Do we need to save such messages in pull requests code? ![123](https://user-images.githubusercontent.com/29621138/204798601-bc374711-6ce2-4d42-8fdd-436d254c830c.png)

I never used them. It may worth to ask other developers.
