### ISSUE TITLE
Question about "unexpected requestId in response"

### ISSUE THREAD

**Issue by tracer0tong** [tarantool/go-tarantool#24]
Hi, guys. 
Sometimes I've got a message in logs "tarantool: unexpected requestId (xxx) in response". I have a question: how correctly work with this exception? Should I resend query or reconnect to database? 
Do you know a reasons of this issue?

**Comment by mialinx** [comment]
Yes, it typically happens after timeouts.
When tarantool doesn't answer in Timeout time, driver drops the request (and you get Timeout error).
Later, when tarantool finally returns the answer, driver can't find coresponding request and logs "unexpected response" error.

Consider increasing Timeout.
