### ISSUE TITLE
Implement PAP-SHA256 auth mechanism 

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/go-tarantool#243]
We need to support a new authorization mechanizm PAP-SHA256, RFC:

https://www.notion.so/tarantool/Authentication-methods-908501aa74834bdea70c384d6df97105

We need:

1. To add Opts.AuthType to force 'chap-sha1' or 'pap-sha256' authorization method here:
https://github.com/tarantool/go-tarantool/blob/d6d0031d7a0ce9959edf57f9407bba9652a37506/connection.go#L215
2. To check `IPROTO_AUTH_TYPE = 0x5b`here:
https://github.com/tarantool/go-tarantool/blob/d6d0031d7a0ce9959edf57f9407bba9652a37506/response.go#L195-L210
and add the information about auth type to IdRequest response.
3. To choose an authorization method by priority: Opts.AuthType -> IPROTO_AUTH_TYPE -> 'chap-sha1' (default).
4. To implement the method `pap-sha256` for authReques according to the RFC:
https://github.com/tarantool/go-tarantool/blob/d6d0031d7a0ce9959edf57f9407bba9652a37506/auth.go
https://github.com/tarantool/go-tarantool/blob/d6d0031d7a0ce9959edf57f9407bba9652a37506/request.go#L598-L603

The connector should refuse to use PAP-SHA256 unless the network channel is encrypted with SSL/TLS.

Linked issues:

https://github.com/tarantool/tarantool/issues/7987
https://github.com/tarantool/tarantool/issues/7988
https://github.com/tarantool/tarantool/issues/7989
https://github.com/tarantool/tarantool-ee/issues/295
https://github.com/tarantool/enterprise_doc/issues/206

**Comment by LeonidVas** [comment]
To be implemented in the EE-version of the connector.

**Comment by LeonidVas** [comment]
The bosses turn the wheel one more time. We implement this feature here.
