### ISSUE TITLE
Use of a Broken or Risky Cryptographic Algorithm

### ISSUE THREAD

**Issue by j10i2** [tarantool/go-tarantool#245]
Hello, Dear Community! 

I mentioned, that in Auth.go code we use a SHA-1 hash function for Authentification purposes. 
![image](https://user-images.githubusercontent.com/61912282/206214481-ae12c3dd-706a-4d17-830b-1003caa79c90.png)

Is it suitable to change this hash function to newer such as SHA-2 or SHA-3? SHA-1 is cryptographically broken and should not be used for secure applications.

Thank you!

**Comment by R-omk** [comment]
https://github.com/tarantool/tarantool/issues/7770
