### ISSUE TITLE
Package with IPROTO constants

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/go-tarantool#267]
Now the main package has some constants:

https://github.com/tarantool/go-tarantool/blob/v1.10.0/const.go

But the approach has disadvantages:

1. Not all constants refer to the IPROTO protocol.
2. It is not always obvious how these constants relate to IPROTO. As example, what is `KeyFetchPos`? It is `IPROTO_FETCH_POSITION`, but I can't confirm this without looking at the Tarantool code. As example, this mismatch of names is confusing when you read [this document ](https://www.tarantool.io/en/doc/latest/dev_guide/internals/iproto/format/) and try to create a request/parse a response.
3. The file is edited manually, it contains only what is needed for the connector.
4. https://github.com/tarantool/go-tarantool/issues/158

It would be nice:

1. To create a separate package (as a part of the connector `https://github.com/tarantool/go-tarantool/iproto` or as a separate package `https://github.com/tarantool/go-iproto` with a separate lifecycle).
2. Periodically auto-generate IPROTO constants from `tarantool/src/box/iproto_{constants, features}.h` with a custom generator for the package.
3. An update requires as few manual actions as possible (start a job on GitHub Actions?). But we could start with `Makefile` targets.

See also:
https://github.com/tarantool/tarantool/issues/7103
https://github.com/tarantool/tarantool/pull/7951
https://go.dev/blog/generate

The idea is a part of a discussion with @unera :
https://www.notion.so/tarantool/Go-replicator-API-d9c982f15df044ee95d5d7d9d1b5505b

**Comment by DifferentialOrange** [comment]
If there is some convenient way to make it language-independent (so it could be used in other connectors), it would be cool.

**Comment by oleg-jukovec** [comment]
It would be nice to parse error codes from `src/box/errcode.h` too:
https://github.com/tarantool/tarantool/blob/b1095c1c3254ce3c2bf1a77bbfef80dfb93725b2/src/box/errcode.h#L54-L321

We already have some of the constants in:

https://github.com/tarantool/go-tarantool/blob/d7a422b425602263eb52e206d98feeb297eb1fa7/errors.go#L62-L174

But it looks outdated.
