### ISSUE TITLE
How to pack varbinary?

### ISSUE THREAD

**Issue by rayman1104** [tarantool/go-tarantool#269]
I have a function in go that calls lua function in router:
```
func (tkv *TarantoolKeyValueStore) put(key string, value []byte) error {
	_, err := tkv.conn.Call("kv_set", []interface{}{key, value})
	return err
}
```

This is the space schema:
```
format = {
  {'key', 'string'},
  {'value', 'varbinary'},
}
```

But unfortunately, I get this error:
`Tuple field 2 (value) type does not match one required by operation: expected varbinary, got string`

This is function in router:
```
function kv_set(key, value)
    local space = "main"
    local router = cartridge.service_get('vshard-router').get('core')
    local bucket_id = router:bucket_id_strcrc32(key)
    local tuple = {
        key,
        value,
        bucket_id,
    }
    router:callrw(bucket_id, "_kv_set", {space, tuple})
end
```
This is function in storage:
```
function _kv_set(space, tuple)
    box.space[space]:put(tuple)
end
```

**Comment by oleg-jukovec** [comment]
https://github.com/tarantool/tarantool/issues/4201

`It should be stored as mp_bin in msgpack.`

You could try to implement a [custom encoder](https://pkg.go.dev/github.com/vmihailenco/msgpack/v5#CustomEncoder) for a custom type. Something like this:

```Go
type varbinary = []byte

func (v varbinary) EncodeMsgpack(encoder *msgpack.Encoder) error {
    return enc.EncodeBytes(([]byte)v) // or try enc.EncodeString((string)v)
}
```

To be honest, I didn't check the code above in a test.

I think we should provide an example in godoc too.

**Comment by rayman1104** [comment]
```
type varbinary []byte

func (v varbinary) EncodeMsgpack(enc *msgpack.Encoder) error {
	return enc.EncodeBytes(v)
}

//...

func (tkv *TarantoolKeyValueStore) put(key string, value varbinary) error {
	_, err := tkv.conn.Call("kv_set", []interface{}{key, value})
	return err
}
```

This is what I tried but it didn't work, unfortunately. Same error.

Fun fact: on the tarantool website it's said that this connector [supports varbinary](https://www.tarantool.io/en/doc/latest/book/connectors/go/#feature-comparison)  😄

**Comment by R-omk** [comment]
@rayman1104, most likely your problem is not related to the go connector

lua always casts binary data to a string

https://github.com/tarantool/tarantool/issues/1629

**Comment by rayman1104** [comment]
I see, if I get it right, it's possible to do via iproto, but not possible by calling lua function. There is also some nasty workaround to do it in lua: https://www.tarantool.io/en/doc/latest/how-to/app/cookbook/#ffi-varbinary-insert-lua

I'm curious though, maybe you know, what is the overhead of storing bytes as strings? Is there any difference in terms of memory consumption at all?

**Comment by R-omk** [comment]
>Is there any difference in terms of memory consumption at all?

they are completely identical.

https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family

**Comment by rayman1104** [comment]
Ok, then I can leave with that. Thanks guys!
