### ISSUE TITLE
Auto Eject Host down from pool connections. 

### ISSUE THREAD

**Issue by BruAPAHE** [tarantool/go-tarantool#272]
Привет, извини, что на русском. Не подскажешь есть ли механизм убирания упавшего тарантула из пула коннектов. Не могу найти в библиотеке. Пакет `connection_pool`. Нашел `Deactivated(conn *tarantool.Connection, role Role) error`
но нет примеров как использовать.

**Comment by oleg-jukovec** [comment]
Добрый день. Совсем убрать на данный момент нельзя.

При падении пул это должен определить с некоторой задержкой и убрать его из списка активных соединений. Но подключаться к этому хосту он по-прежнему будет пытаться. А после успешного подключения - слать запросы.

**Comment by BruAPAHE** [comment]
@oleg-jukovec Почему то не работает чекер, поставил на 1 секунду. Запросы все равно летят в недоступный контейнер.
`connect, err := connection_pool.Connect([]string{"0.0.0.0:3302", "0.0.0.0:3303"}, tnt.Opts{
		User:      "guest",
		Timeout:   6 * time.Second,
		Reconnect: 10 * time.Second,
	})
	if err != nil {
		log.Fatalln(err)
	}

	for {
		var result any
		log.Println(connect.GetTyped("tester2", "primary", tnt.IntKey{I: 1}, &result, connection_pool.ANY))
		log.Println(result)
		time.Sleep(1 * time.Second)
	}`
	`2023/03/13 14:26:53 <nil>
2023/03/13 14:26:53 [1 Roxette 1986]
2023/03/13 14:26:54 client connection is not ready (0x4000)
2023/03/13 14:26:54 <nil>
2023/03/13 14:26:55 <nil>
2023/03/13 14:26:55 [1 Roxette 1986]
2023/03/13 14:26:56 client connection is not ready (0x4000)
2023/03/13 14:26:56 <nil>
2023/03/13 14:26:57 <nil>
2023/03/13 14:26:57 [1 Roxette 1986]
2023/03/13 14:26:57 tarantool: reconnect (7/0) to 0.0.0.0:3302 failed: dial tcp 0.0.0.0:3302: connect: connection refused
2023/03/13 14:26:58 client connection is not ready (0x4000)
2023/03/13 14:26:58 <nil>
`

**Comment by oleg-jukovec** [comment]
Попробуйте убрать из опций `Reconnect: 10 * time.Second`, если сработает то это какой-то бажок.

**Comment by BruAPAHE** [comment]
@oleg-jukovec помогло, спасибо!

**Comment by BruAPAHE** [comment]
close

**Comment by oleg-jukovec** [comment]
Нужно будет посмотреть бажок внимательней. Хоть и некретично, но неприятно.
