### ISSUE TITLE
[]byte instead []interface

### ISSUE THREAD

**Issue by monopollly** [tarantool/go-tarantool#29]
Hi, 

How can I get raw []byte response instead []interface from tarantool when I making a Call?

**Comment by funny-falcon** [comment]
I don't know exact way.

But may call CallTyped and pass a custom registered type:
https://godoc.org/gopkg.in/vmihailenco/msgpack.v2#Register
https://godoc.org/gopkg.in/vmihailenco/msgpack.v2#CustomDecoder

Unfortunately, decoder methods will receive `msgpack.Decoder` and it has no access to underlying reader.
But if your requirement is not to send it further "as is", but parse it, then `msgpack.Decoder` has useful methods: `DecodeInt`, `DecodeMapLen`, `DecodeString`, etc.

**Comment by funny-falcon** [comment]
Could this issue be closed?

**Comment by monopollly** [comment]
yep, calltyped is a good solution. thanks

**Comment by DenisCheremisov** [comment]
Vote for this one. Tarantool is nice but tooling and libs are terrible. Including this one. Why on earth did you decide to use `[][]interface{}`?

**Comment by funny-falcon** [comment]
I'll close it for now, because there is single reference to `[][]inteface{}` at the moment - at the `(*Response).Tuples`
