### ISSUE TITLE
Remove `box.info.cluster.uuid` usage from tests

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/go-tarantool#293]
go-tarantool integration tests fail on one of the Tarantool 3.0 PRs: https://github.com/tarantool/tarantool/pull/8289 https://github.com/tarantool/tarantool/actions/runs/5011819703/jobs/8984720081?pr=8289

The reason seems to be in `./crud/testdata/config.lua` referencing `box.info().cluster.uuid`.
The https://github.com/tarantool/tarantool/pull/8289 PR renames `box.info.cluster.uuid` to `box.info.replicaset.uuid`.

So the test should prefer `box.info.replicaset.uuid` and only fall back to `box.info.cluster.uuid` if `box.info.replicaset.uuid` is missing.

**Comment by oleg-jukovec** [comment]
The test suite can not load test config for Tarantool:
https://github.com/tarantool/go-tarantool/blob/cdfcddffafc5beafe300a51b18edbb978ed2a2ec/crud/testdata/config.lua

The problem source is `vshard`:
```
$ grep "box.info.cluster" -r .
./crud/testdata/.rocks/share/tarantool/vshard/storage/init.lua:    local uuid = box.info.cluster.uuid
```

So the issue should be fixed in `vshard`->`crud`, we need just to bump a used `crud` version.

**Comment by Serpentian** [comment]
Vshard's fixes are in master now
