### ISSUE TITLE
Asyncio Tarantool Queue

### ISSUE THREAD

**Issue by FireGM** [tarantool/go-tarantool#31]
what about interface for it?

**Comment by funny-falcon** [comment]
If you describe desired interface, then it could happen.
(note: do not put much magic in, please).

**Comment by FireGM** [comment]
`type Queue interface {
	GetTube(name string) (*Tube, error)
	NewTube(name string, ttl int, delay int) (*Tube, error)
	DeleteTube(name string) (*Tube, error)
}

type Tube interface {
	Next() (TubeData, error)
	Put(data string) (*Tube, error)
}

type TubeData interface {
	GetId() int
	Ack() error
	Release() error
	Delete() error
	GetData() string
}

func main() {
	client, _ := tarantool.Connect(server, opts)
	tube := client.Queue.GetTube("my_tube").(Tube)
	go func() {
		for i := 0; i < 10; i++ {
			tube.Put("new_data")
		}
	}()
	for td, err := tube.Next(); err == nil {
		fmt.Println(td.GetData()) // new_data
		td.Ack()
	}
}`

**Comment by FireGM** [comment]
```type Queue interface {
	GetTube(name string) (*Tube, error)
	NewTube(name string, ttl int, delay int) (*Tube, error)
	DeleteTube(name string) (*Tube, error)
}

type Tube interface {
	Next() (TubeData, error)
	Put(data string) (*Tube, error)
}

type TubeData interface {
	GetId() int
	Ack() error
	Release() error
	Delete() error
	GetData() string
}

func main() {
	client, _ := tarantool.Connect(server, opts)
	tube := client.Queue.GetTube("my_tube").(Tube)
	go func() {
		for i := 0; i < 10; i++ {
			tube.Put("new_data")
		}
	}()
	for td, err := tube.Next(); err == nil {
		fmt.Println(td.GetData()) // new_data
		td.Ack()
	}
}```

**Comment by NikSmith** [comment]
Hi. What about this?

**Comment by funny-falcon** [comment]
Sorry, will try to do this week.

**Comment by funny-falcon** [comment]
Interface for queue were merged. Could I close this issue? or you have some additional thoughts on.

**Comment by NikSmith** [comment]
Правильно я понимаю, что чтобы реализовать постоянное чтение из очереди, нужно task проверять на nil ?

`
go func() {
		for {
			task, err := q.TakeTimeout(1 * time.Second)
			if err != nil {
				fmt.Printf("error in take with is %v", err)
				continue
			}

			if task == nil {
				continue
			}
			fmt.Println("data_1: ", task.Data())
			task.Ack()
			
		}
`

**Comment by funny-falcon** [comment]
Запрос с бесконечным таймаутом? это, мне кажется, проблематично.
Не знаю, как со стороны очереди, но со стороны драйвера это сейчас точно проблематично.

Как вариант, можно сделать обёртку, которая на nil сама делает retry.

Ещё вариант, создать коннект без таймаута, очередь без таймаута, и q.Take() - это будет похоже на то, что ты предлагаешь?
Если нет, то как твой итератор должен работать в присутствии таймаутов?

**Comment by NikSmith** [comment]
Мне кажется мы не совсем поняли друг друга. 
Я говорю о чтении самой очереди, меня смутило, что необходимо проверять после Take сам таск на nil в бесконечном цикле для поддержания постоянного чтения очереди.

Начал тестировать и пока не могу понять почему не работает Delay, правильно я понимаю, что это возможность отложить получение таска воркером?

**Comment by funny-falcon** [comment]
> Я говорю о чтении самой очереди, меня смутило, что необходимо проверять после Take сам таск на nil в бесконечном цикле для поддержания постоянного чтения очереди.

Пусть не смущает. Если есть мысль, как "улучшить", я готов рассмотреть пул реквест.

> Начал тестировать и пока не могу понять почему не работает Delay, правильно я понимаю, что это возможность отложить получение таска воркером?

Скорее всего, да. Я сам очередями не пользовался, так что мне трудно сказать. Посмотри здесь: https://github.com/tarantool/queue , и попробуй.

**Comment by NikSmith** [comment]
Ок.
По delay кажется понял в чем проблема, нужно указывать другой тип очереди.
В любом случае спасибо за реализованную поддержку очередей.

**Comment by funny-falcon** [comment]
Ну, спасибо по большей части не мне. Я только замержил и дошлифовал.

Я понимаю, что можно закрыть тикет. Не стесняйся открывать новые, ок?
