### ISSUE TITLE
Typed calls without registration

### ISSUE THREAD

**Issue by DenisCheremisov** [tarantool/go-tarantool#33]
Types registration is somewhat questionable approach, definitely not goish one. Could we have
```CallXXX```
method with signature like
```go
func (tc *Connection) CallXXX(method string, []interface{}, sucker Decoder) error
```
instead?
Where
```go
type Decoder interface {
    Decode([]byte) error
}
```
?

**Comment by funny-falcon** [comment]
`sucker` (as you wrote) is a really good name.
But why do you didn't read documentation of message pack?
Here is a link for you: https://godoc.org/gopkg.in/vmihailenco/msgpack.v2#pkg-examples
Read and enjoy.
