### ISSUE TITLE
v2: consider reworking timeout value

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/go-tarantool#342]
crud operations timeout is an optional uint:
https://github.com/tarantool/go-tarantool/blob/a664c6bbb6a1f21aecfccf199858e19a21857700/crud/options.go#L235

yet it is not forbidden to request a float timeout for a crud operation (for example, it is the only way to set 100 ms timeout).

**Comment by oleg-jukovec** [comment]
Ok, we could to update it.
