### ISSUE TITLE
crud: typed batches

### ISSUE THREAD

**Issue by a1div0** [tarantool/go-tarantool#365]
Improvement suggested.
Let's say I set the following line:
``` go
enter Row struct {
   _msgpack struct{} `msgpack:",asArray"` //nolint: structcheck,unused
   Identifier uint `msgpack:"id"`
   BucketId *uint `msgpack:"bucket_id"`
   Too uint `msgpack:"too"`
   Foo string `msgpack:"foo"`
}
```

Make an improvement so that you can pass data in this structure in batches, for example to a method
``` go
// Row --> batch --> and ..
req := crud.MakeInsertObjectManyRequest("test").Objects(batches[i]) // <-- here
```

**Comment by oleg-jukovec** [comment]
The problem: it is unable to use a batch of tuples as an `Objects` argument.
The possible solution: `Objects` should accept `interface{}` as an arguments instead of `[]crud.Tuple`.

**Comment by oleg-jukovec** [comment]
You although will need to use `MakeInsertManyRequest` to insert tuples as arrays, `MakeInsertObjectManyRequest` for tuples as maps. See new examples from #375 .
