### ISSUE TITLE
Cant GetTyped if one of tarantool response keys is non-string typed

### ISSUE THREAD

**Issue by KaymeKaydex** [tarantool/go-tarantool#368]
msgpack: invalid code=1 decoding string/bytes length

https://github.com/vmihailenco/msgpack/blob/19c91dfdfa062658c39d9321be26163fc5833bd1/decode_string.go#L31

**Comment by KaymeKaydex** [comment]
<img width="494" alt="Снимок экрана 2024-01-02 в 22 05 34" src="https://github.com/tarantool/go-tarantool/assets/43151027/1c39679d-409a-4a69-be04-ee201e54cde3">
but data non-empty

**Comment by oleg-jukovec** [comment]
Please give an example of the code in which you decode the response and the response decoded as {}interface with `Get()`.

**Comment by oleg-jukovec** [comment]
I got it. You need to write a custom decoder for this cases, as example:

```Go
type testReproducer368 struct {
	Value int
	Foo   string
}

func (t *testReproducer368) DecodeMsgpack(d *msgpack.Decoder) error {
	var (
		err error
		l   int
	)
	if l, err = d.DecodeMapLen(); err != nil {
		return err
	}
	for i := 0; i < l; i++ {
		key, err := d.DecodeInterface()
		if err != nil {
			return err
		}
		value, err := d.DecodeInterface()
		if err != nil {
			return err
		}
		switch key {
		case int8(34):
			t.Value = int(value.(int8))
		case "foo":
			t.Foo = value.(string)
		}
	}
	return nil
}

func TestReproducer368(t *testing.T) {
	conn := test_helpers.ConnectWithValidation(t, dialer, opts)
	defer conn.Close()

	test := []testReproducer368{}
	err := conn.Do(NewEvalRequest("return {[34] = 2, foo = 'bar'}")).GetTyped(&test)
	require.NoError(t, err)
	require.Equal(t, []testReproducer368{testReproducer368{2, "bar"}}, test)
}
```

You could see examples of the custom decoders in the connector code or in the `msgpack` library.

**Comment by oleg-jukovec** [comment]
The reason in the `msgpack` library implementation, we can't fix it on our side.

**Comment by nurzhan-saktaganov** [comment]
Yes, the reason is that `msgpack` library implementation can't decode map into struct, if this map contains non-string keys.
See issue: https://github.com/vmihailenco/msgpack/issues/372
