### ISSUE TITLE
Error: Invalid MsgPack - packet body (0x14)

### ISSUE THREAD

**Issue by monopollly** [tarantool/go-tarantool#38]
Когда делаешь запрос 
Если в базе есть какие данные все нормально, 
коннектор отдает данные правильно, без ошибок, 
но если данных нет (nil) то получаем 
```diff
- Error: Invalid MsgPack - packet body (0x14)
```
С чем это может быть связано?
И CallTyped и CallTyped17 так отвечают
```go
res := &[]model.Event{}
err := a.DB.Conn.CallTyped("get", id, &res)
```
Как добится чтобы ошибки не было а то она немного путает, должен быть nil везде

**Comment by jetuuuu** [comment]
Какая версия тарантула ?

**Comment by funny-falcon** [comment]
CallTyped что-то подразумевает. Например, то, что скорее всего у вас своя процедура распаковки. Может есть смысл в ней покопаться? чтобы она правильно реагировала на nil ?
Или вы полагаетесь на встроенный reflection в msgpack?

В общем, пожалуйста, напишите пример, чтобы можно было воспроизвести (с конфигом тарантула, описанием типов, и прочее).

PS, почему `res = &[]model.Events{}` ? и потом `&res` ? мне пока сложно понять, но возможно так и надо. В любом случае, почему не `var res *[]mode.Events` ? И почему не работает `var res []mode.Events`?

**Comment by funny-falcon** [comment]
yeah, and lets use english :-) cause we hope Tarantool will be popular worldwide

**Comment by monopollly** [comment]
all is ok, just wrong return from stored procerure... my fault
I returned empty table {} instead just nil
thanks
