### ISSUE TITLE
Can't get space length via tarantool.crud

### ISSUE THREAD

**Issue by Vlad97vsv** [tarantool/go-tarantool#394]
Can't get space length via crud.len

I get an error: `array len doesn't match: 1`

db - is connected ConnectionPool 
```golang
func getLen() uint64 {
	space := "test_space"
	req := tarantoolcrud.MakeLenRequest(space)
	data := tarantoolcrud.LenResult{}
	if err := db.Do(req, tarantoolpool.ANY).GetTyped(&data); err != nil {
		panic(err)
	}
	fmt.Println(data.Value)
	return data.Value
}
```
`>>> panic: array len doesn't match: 1`

When I use Count query everything is ok.
```golang
func getCount() uint64 {
	space := "test_space"
	req := tarantoolcrud.MakeCountRequest(space)
	data := tarantoolcrud.CountResult{}
	if err := db.Do(req, tarantoolpool.ANY).GetTyped(&data); err != nil {
		panic(err)
	}
	fmt.Println(data.Value)
	return data.Value
}
`>>> 10000`
```

---
If you look at what arrives, you can see that only 1 entry in the array arrives for crud.len. And for count there are 2 entries:

```golang
func (r *MetaTntRepositoryVShard) getCount2() {
	space := "test_space"
	req := crud.MakeCountRequest(space)
	if data, err := db.Do(req, tarantoolpool.ANY).Get(); err != nil {
		panic(err)
	} else {
		fmt.Printf("%+v\n", data)
	}
}
```
<img width="346" alt="image" src="https://github.com/tarantool/go-tarantool/assets/33463417/90322a80-a15c-4856-8fc3-1b4a3b904a32">

The error occurs precisely during serialization. Therefore the code below works
```golang
func (r *MetaTntRepositoryVShard) getLen2() {
	space := "test_space"
	req := crud.MakeLenRequest(space)
	if data, err := db.Do(req, tarantoolpool.ANY).Get(); err != nil {
		panic(err)
	} else {
		fmt.Printf("%+v\n", data)
	}
}
```
<img width="394" alt="image" src="https://github.com/tarantool/go-tarantool/assets/33463417/69c13be0-3ff1-4b45-a7f5-2070504c91f5">

---
Crud is installed, everything works correctly via tarantoolctl crud.len works.

---
The error seems clear, but I can’t understand why tarantool returns 1 field when asking for length.

---
golang version: 1.21.1
lib: go-tarantool/v2 2.0.0
OS: MacOs 
tarantool version: 2.11

**Comment by DifferentialOrange** [comment]
> The error seems clear, but I can’t understand why tarantool returns 1 field when asking for length.

To be honest, it's more weird that every (or almost every) other method return explicit `result, nil` in case of success.

**Comment by oleg-jukovec** [comment]
Thank you for the issue, are you sure that go-tarantool version is exactly v2.0.0? It should be fixed with:
https://github.com/tarantool/go-tarantool/commit/c3ba5b59b7d1d7fdedba1e914925abe7d6b1c77d

Please, write a `crud` version because  I can’t reproduce the problem.

**Comment by Vlad97vsv** [comment]
I use `github.com/tarantool/go-tarantool/v2 v2.0.0-20230823074441-d8df65dcd0f2`. 

---
Thank you. I'll try to update to 2.1.0 and will be back with feedback

**Comment by Vlad97vsv** [comment]
With the update to version 2.1.0 the problem disappeared.

Thank you very much for the quick response
