### ISSUE TITLE
Сообщение об ошибке не соотвествует ошибке.

### ISSUE THREAD

**Issue by MichaelMonashev** [tarantool/go-tarantool#41]
Я запустил тарантул, задав box.cfg{listen = "127.0.0.1:3301"} . А в клиенте в Opts задал по ошибке юзера и пароль. Клиент естесвенно не коннектится и выдаёт неверное описание ошибки: client connection is not ready (0x4000) . По нему и по исходникам очень неочевидно, что дело именно в том, что логин и пароль причина ошибки.

**Comment by funny-falcon** [comment]
```go
package main

import (
	"fmt"
	"github.com/tarantool/go-tarantool"
	"time"
)


var server = "127.0.0.1:3013"
var opts = tarantool.Opts{
	Timeout: 500 * time.Millisecond,
	User:    "test",
	Pass:    "test",
}

func main() {
	conn, err := tarantool.Connect(server, opts)
	if err != nil {
		fmt.Printf("conn: %v\n", err)
		return
	}
	defer conn.Close()
}
```
```
$ go run auth.go
conn: User 'test' is not found (0x2d)
```
 ЧЯДНТ?

**Comment by funny-falcon** [comment]
Ah, I see: if Reconnect is non-zero, then it is really `connection is not ready` . I'll think a bit.

**Comment by funny-falcon** [comment]
I've added special case for UserNotFound and PasswordMismatch.

https://github.com/tarantool/go-tarantool/commit/a1a677f664b6ae04d686d884a9cf055f94f25059

**Comment by funny-falcon** [comment]
Unfortunately, it will not work if tarantool is not running at the application start moment, cause conn.loadSchema will still fail with `client connection is not ready (0x4000)` immediately.

But probably it is correct behavior: connection is really not ready :-) cause tarantool is not running.

Should I close the issue?

**Comment by MichaelMonashev** [comment]
Yes.
