### ISSUE TITLE
Data race on timeouts

### ISSUE THREAD

**Issue by sisoftrg** [tarantool/go-tarantool#43]
Hello. I use relative small timeouts for some reason and from time to time it occurs.
Debugging my code under race detector I got the following data race few times:

```
2017-06-25 02:01:11.6975 pub term error: client timeout for request 19628700 (0x4003)
2017-06-25 02:01:11.7933 pub term error: client timeout for request 19628716 (0x4003)
==================
WARNING: DATA RACE
Write at 0x00c420188098 by goroutine 14:
  github.com/tarantool/go-tarantool.(*Connection).timeouts()
      /home/go/src/github.com/tarantool/go-tarantool/connection.go:741 +0x633

Previous read at 0x00c420188098 by goroutine 47:
  github.com/tarantool/go-tarantool.(*Future).send()
      /home/go/src/github.com/tarantool/go-tarantool/request.go:383 +0x89
  github.com/tarantool/go-tarantool.(*Connection).Call17Async()
      /home/go/src/github.com/tarantool/go-tarantool/request.go:334 +0x101
  github.com/tarantool/go-tarantool.(*Connection).Call17()
      /home/go/src/github.com/tarantool/go-tarantool/request.go:113 +0x64
[my code skipped]

Goroutine 14 (running) created at:
  github.com/tarantool/go-tarantool.Connect()
      /home/go/src/github.com/tarantool/go-tarantool/connection.go:248 +0xb14
[my code skipped]

Goroutine 47 (running) created at:
[my code skipped]
==================
2017/06/25 02:01:11 tarantool: unexpected requestId (19628700) in response
2017/06/25 02:01:11 tarantool: unexpected requestId (19628716) in response
```

using latest code from github (728550a7ad41522305a52bce369aa7493b97916d).

Not error yet, but I think it should be checked and fixed.

**Comment by funny-falcon** [comment]
So your request is timeouted before actually sent? What are reasons for setting such small timeout?

I will think about. It will quite hard to fix without significant performance drop.

**Comment by sisoftrg** [comment]
No, request is sent to server, but not replied in time and timeout occurs. According to last lines (``unexpected requestId``) server replied some time later.

Small timeouts used because of near-realtime service and correct rejects preffered to upstream timeouts. Anyway, increasing timeouts decreases count of it but not solve issue.

**Comment by funny-falcon** [comment]
Please, test it. If error still happens, fill free to reopen.
