### ISSUE TITLE
Limit in select?

### ISSUE THREAD

**Issue by sylogex** [tarantool/go-tarantool#44]
Hi! I am very surprised, why there is no possible to do select query without limit?

**Comment by funny-falcon** [comment]
Why do you want to do select without limit?

Note, you may specify limit 1000000000. But if you really have 1000000000 tuples, tarantool will serve only this query until all 100000000 tuples will be sent. No other queries will be processed at the same moment. (well, it is not exact truth, but quite close to truth).

And all those 1000000000 tuples will be materialized in go connector. Even if tuple contains one integer, response first will be read into 1-4GB buffer, then deserialized into 4GB array (if you use typed query).

So I ask you again: why do you want select without limit?
Perhaps I just don't understand exactly your use case.

**Comment by sylogex** [comment]
Simply in the original (in lua, tarantool console) there is no limit in plane select. That's why I asked.  I looked at the type of the variable - it was uint32 - values is 0 to 4294967295 and I take this. Anyway, thank you! Without this library work with tarantool in golang would be very sad! )

**Comment by funny-falcon** [comment]
There is default limit in lua's select (iirc, i could be mistaken)
It is just not so cheap to make default value in Go: either it is hidden allocation, or another function name. So we decided to make it always explicit.

May be, next api version (if ever happens) will use struct as named arguments, so omitted fields will be default 

May this issue be closed?

**Comment by sylogex** [comment]
Maybe in lua's select the limit not explicitly declared and maybe exist default limit, I do not know exactly, because in documentation i don't find something about it.

Yep, you can close the issue. Thank you for replay and for your work! Спасибо )
