### ISSUE TITLE
Remove log usage from connection.go

### ISSUE THREAD

**Issue by tracer0tong** [tarantool/go-tarantool#45]
Could you remove calls of log.Printf from connection.go?
This is only the file with logging API calls, and it throws messages directly to stdout by default. In some cases, when logging changed to non-standard library, this messages couldn't be interrupted.

**Comment by funny-falcon** [comment]
I certainly could not remove logging. I could change it to something else. I'm open for discussion.

BTW: you could replace output of standard library to any `io.Writer` : https://golang.org/pkg/log/#SetOutput . Why you didn't do it?

**Comment by mialinx** [comment]
We could add logger field to the connection, and create default implementation writing to STDERR.
Anyone can change implementation as needed.

**Comment by tracer0tong** [comment]
@mialinx good idea, I have my own customer logger, so I can just define it as a parameter.

**Comment by funny-falcon** [comment]
Do I understand correctly, that all we need is:
```go
type Logger interface {
     Printf(format string, v ...interface{})
}
type defaultLogger struct{}
func (d defaultLogger) Printf(format string, v ...interface{}) {
     log.Printf(format, v...)
}
type Opts struct {
// ....
     Logger Logger
}
func Connect() () {
// ....
    if conn.opts.Logger == nil {
        conn.opts.Logger = defaultLogger{}
    }
}
```

**Comment by funny-falcon** [comment]
Or we need to extend logger usage (for example, use something similar to pkg/syslog) ?

**Comment by tracer0tong** [comment]
@funny-falcon I think your variant is fine. If conn.opts.Logger == nil, you can use logger from standard logging library.
