### ISSUE TITLE
Unsafe type assertion

### ISSUE THREAD

**Issue by jaberwoky** [tarantool/go-tarantool#49]
https://github.com/tarantool/go-tarantool/blob/c2105bc5a0e676a86c1739f146468a1f44ab4715/connection.go#L74

Hi, thanks for the great repo, but I've got a panic using the recent version of go-tarantool client.  Here is the stack trace:

collector1 panic: interface conversion: interface {} is *tarantool.Response, not tarantool.Response
collector1
collector1 goroutine 169127 [running]:
collector1 github.com/tarantool/go-tarantool.defaultLogger.Report(0x7, 0xc4208e8100, 0xc420054f50, 0x1, 0x1)
collector1     /home/sites/go/src/github.com/tarantool/go-tarantool/connection.go:74 +0x6ad
collector1 github.com/tarantool/go-tarantool.(*defaultLogger).Report(0xafa830, 0x7, 0xc4208e8100, 0xc420054f50, 0x1, 0x1)
collector1     <autogenerated>:1 +0x66
collector1 github.com/tarantool/go-tarantool.(*Connection).reader(0xc4208e8100, 0xc4201ca780, 0xab2b60, 0xc420148028)
collector1     /home/sites/go/src/github.com/tarantool/go-tarantool/connection.go:638 +0x21c
collector1 created by github.com/tarantool/go-tarantool.(*Connection).dial
collector1     /home/sites/go/src/github.com/tarantool/go-tarantool/connection.go:411 +0x641

Sadly, I don't know how to reproduce it, but it is obvious that the client panics because of unsafe type assertion when handling error "connection %s got unexpected resultId". The resp value being passed to conn.opts.Logger.Report() method call is of *Response type whilst in this method there is an attempt to extract Response from it. Please see:

https://github.com/tarantool/go-tarantool/blob/master/connection.go#L638
https://github.com/tarantool/go-tarantool/blob/master/connection.go#L74

I'm using tarantool 1.7.5, golang 1.9 and CentOS 6.9.

Thanks.

**Comment by funny-falcon** [comment]
My bad :-(
