### ISSUE TITLE
Wrong behavior when try to connect to an inaccessible tarantool instance.

### ISSUE THREAD

**Issue by donmikel** [tarantool/go-tarantool#50]
If specified opts.Reconect > 0, and we are trying to connect to an inaccessible tarantool instance, tarantool.Connect returns nil, although it should notThis happens after an unsuccessful attempt to obtain a schema.

**Comment by funny-falcon** [comment]
It is hard to fix. Fix will rely on schema reloading, that is not implemented yet.
If you use numeric ids for spaces and indices, you may skip schema loading.
https://github.com/tarantool/go-tarantool/blob/master/connection.go#L293

Schema reloading is in TODO, but I don't know when I will do it.

**Comment by donmikel** [comment]
Thanks, i already did this workaround.

**Comment by mialinx** [comment]
BTW, opt.Reconnect is intentionally ignored during initial connect.
Reconnect is useful feature in persistent running demon, and frustrating in scripts or during demon restart, as it hangs up the process instead of reporting an error.

**Comment by funny-falcon** [comment]
@mialinx +1.
But script shall not set Reconnect, and requests are aborted after each failing reconnect attempt.
Therefore, doubtfully process will silently hang.

**Comment by Totktonada** [comment]
Am I understand right: 'inaccessible instance' is one, where we have no `_vspace` and `_vindex` access (but able to call functions)? That's strange: those views are specifically designed to show only spaces, to where a user has accesses, and the views are accessible by default. Are accesses to them revoked manually with some idea in the mind?

An option to skip schema loading may be useful anyway, see https://github.com/tarantool/tarantool/issues/4789.

**Comment by Totktonada** [comment]
Sorry, I can't understand the problem without additional infromation or a reproducer script. Feel free to reopen the issue with extra details if you're interested in a fix.
