### ISSUE TITLE
Complicated request

### ISSUE THREAD

**Issue by artjoma** [tarantool/go-tarantool#57]
Hi folks!
  I have a question about how to use a select by 4 fields. Two values simple equals and third value between time(uint32) range :  
field1val = Xval and field2val = Yval and field3val < Zval and Zval < field4val 

Or I should use SQL? 
Do this library support  SQL or how I can connect to Tarantool using plain SQL? SQL driver from MySQL for example? Any SQL integration examples?

**Comment by artjoma** [comment]
Solved with the procedure. What about SQL ?

**Comment by funny-falcon** [comment]
SQL support in tarantool is in pre-beta stage (not alpha already, but not beta yet :-) ). Probably this driver will eventually support sql.

**Comment by artjoma** [comment]
"Probably this driver will eventually support" I hope!
If I currently use Tarantool(1.9) with LUA mode (golang []interface{}{} data model). Can I use SQL after Tarantool upgrade with SQL support? Or I should migrate all data to SQL tables and after can use plain SQL queries?
