### ISSUE TITLE
Example for inserting tuple with byte slice

### ISSUE THREAD

**Issue by artjoma** [tarantool/go-tarantool#59]
I try to write tuple where one fields is byte slice:
`client.Insert(TEST_SPACE, []interface{}{"testStr", cdata, "param1"})`
cdata - is []byte slice
lua space :
```
{name = 'KEY',       type = 'string'},
{name = 'CDATA',          type = 'array'},
```
Err: `panic: Tuple field 2 type does not match one required by operation: expected array (0x17) [recovered]
	panic: Tuple field 2 type does not match one required by operation: expected array (0x17)`
Could you please present some example.

**Comment by funny-falcon** [comment]
Can you write full reproduction, please?
PR with failing test will be great. But lua script with table creation and small go program that tries to insert is also will be good.

As far as I understand, you want to store "blob". But "array" is not "blob" in message pack. In msgpack array is an array of "generic values", not bytes.

In Go "byte" is alias for uint8, therefore `[]byte` is alias for `[]uint8` . So it is alway treated as "blob".

If you really want to store "array of small intergers", then use `[]int8` or slice of other integer type (`[]uint16`, `[]uint32`, `[]uint`).

If I didn't understand you correctly, I'm waiting for reproduction case and comments.

**Comment by artjoma** [comment]
I understand. I can't use []int8(overflow), using []uint16 it's 2 bytes per position. Will use base58 and store like string. Cheers!

**Comment by funny-falcon** [comment]
Looks like you don't understand msgpack well.

Msgpack will always use smallest size for your integer despite of type on Go's size (at least, if library does job well). So even if you use `[]int64` but all numbers are less than 128, msgpack will use one byte per number to store that slice.

(Please, recheck my sentence. There could be corner cases in used library).

Btw, why base58 ? Why not base64? Base64 is compacter and computation lighter for encoding.

**Comment by artjoma** [comment]
Чтобы сохранить []uint8 со значениями >128, нужно конвертить в []int16. не фан.

**Comment by funny-falcon** [comment]
Так разница только в go коде. Или они тебе такими приезжают?
Кстати, учти, что в msgpack числа больше 128 и так будут занимать 2 байта.
Ну ладно, думаю разобрались. Закроешь?

**Comment by artjoma** [comment]
Приезжают. Теперь понятна механика. Спасибо за разяснеие. Было бы здорово если бы добавили примеры по go + array (test). Наверно я не один такой, кто столкнулся с этим.
