### ISSUE TITLE
Field offset has type uint32

### ISSUE THREAD

**Issue by artjoma** [tarantool/go-tarantool#60]
Почему в Select() поле offet uint32 ?

```
func (conn *Connection) Select(space, index interface{}, offset, limit, iterator uint32, key interface{}) (resp *Response, err error) {
	return conn.SelectAsync(space, index, offset, limit, iterator, key).Get()
}
```
Хотя оно потом сериализируется в uint64:
```
func (req *Future) fillIterator(enc *msgpack.Encoder, offset, limit, iterator uint32) {
	enc.EncodeUint64(KeyIterator)
	enc.EncodeUint64(uint64(iterator))
	enc.EncodeUint64(KeyOffset)
	enc.EncodeUint64(uint64(offset))
	enc.EncodeUint64(KeyLimit)
	enc.EncodeUint64(uint64(limit))
}
```
Можете прояснить.

**Comment by funny-falcon** [comment]
Потому что EncodeUint64 требует uint64. А все остальные методы кодирования unsigned integer всё равно фолбэчатся до EncodeUint64, так что просто прослойка меньше.
А в Select оно uint32 потому что вы точно не хотите пропускать больше 4х миллиардов записей. Если же вы хотите, то это не к нам, для этого есть лечебные заведения. (шутка. без обид, ок?)

**Comment by funny-falcon** [comment]
Можно закрывать?

**Comment by artjoma** [comment]
)))
