### ISSUE TITLE
I can not get the response via conn.Eval .

### ISSUE THREAD

**Issue by zlinwei** [tarantool/go-tarantool#61]
My code : 
`resp, err := conn.Eval(`box.space.test:select{}`, []interface{}{})`

The box.space.test has two records.
But I got the resp.Data was a empty slice. 

Thanks.

**Comment by zlinwei** [comment]
Sorry The code:
resp, err := conn.Eval(`box.space.test:select{}`, []interface{}{})

**Comment by zlinwei** [comment]
Sorry, the code : "box.space.test:select{}"

**Comment by funny-falcon** [comment]
Don't you forget `return`? Lua doesn't return without return.

**Comment by zlinwei** [comment]
Thank you very much. I got the right response. 👍 👍 👍
