### ISSUE TITLE
Could I use SQL syntax to query to Tarantool?

### ISSUE THREAD

**Issue by zlinwei** [tarantool/go-tarantool#62]
Like this:
resp, err := conn.Eval(`SELECT * FROM table1 WHERE column1 = 1;`, []interface{}{})

Because I don't like to use the 'box.sql.execute'.

**Comment by eaglemoor** [comment]
What prevents you from doing a wrapper over conn and inserting the Eval function there?

**Comment by Totktonada** [comment]
Let's consider this issue as 'bare minimum SQL support': just IPROTO_EXECUTE, without prepared statements and extended metainfo.

I would like to see an API proposal before we'll start the implementation.

**Comment by ligurio** [comment]
Probably we need to create PR for [docs](https://www.tarantool.io/en/doc/latest/book/connectors/#feature-comparison) too, where update status of SQL support in connector.
Relevant file in doc repository is https://github.com/tarantool/doc/blob/latest/doc/book/connectors/__go.rst.
