### ISSUE TITLE
V2 proposals

### ISSUE THREAD

**Issue by funny-falcon** [tarantool/go-tarantool#65]
Please, write your wishes for v2 version of this library.
Tend to write one wish per comment, so others may vote for them separately.

**Comment by funny-falcon** [comment]
Proposal:
usage of context.Context should be at least possible. It certainly ought to be for connection establishmend and lifetime.
Usage of Context for requests is quite debatable. Probably, it will be possible, but will not be primary interface. Or it will be documented, that for performance reason it is better to omit context.

**Comment by eaglemoor** [comment]
@Sulverus I think, sharding is a business logic. Not connection library. You can use connections pool and `func (p *Pool) Conn(id int) *tarantool.Connection` to implement sharding in your code.

**Comment by Sulverus** [comment]
Ok. So my vote for schema reloading (it's already implemented in lua netbox and probably in python client)

**Comment by bofm** [comment]
Virtual cursors.

Given an index, an iteration order and batch size, provide an easy way to lazy-iterate over the indexed data.

**Comment by eaglemoor** [comment]
@bofm can you give some examples ?

**Comment by eaglemoor** [comment]
v2 add more examples & benchmarks with Docker Tarantool

**Comment by funny-falcon** [comment]
> Virtual cursors.
> Given an index, an iteration order and a batch size, provide an easy way to lazy-iterate over the indexed data.

It could be done by remembering last "key" and issueing next query with "> last_key", if there is an btree index.
Do you recognize, there is no way to make it consistent? ie there will be no any transaction isolation.

I suppose, it could be done as a helper. But not sure. To extract "key" from typed record, a lot of magic should happen. Since there are custom deserializers (DecodeMsgpack), looks like there will be separate user-given function to extract keys.

**Comment by funny-falcon** [comment]
btw, everyone is happy with `vmihailenco/msgpack` ?
Or is there more preffered library across go-tarantool users?

**Comment by eaglemoor** [comment]
`vmihailenco/msgpack` is default native msg pack library, no? But I think we need and support Big.* type :))

**Comment by AlekSi** [comment]
I wish there were the CHANGELOG.md.

**Comment by FZambia** [comment]
Had a time to experiment with Tarantool, created an opinionated client https://github.com/FZambia/tarantool based on this one - maybe some of its changes will be interesting for v2, sorry for not sending pr @funny-falcon - too many changes, it's pretty hard to imagine there will be a full match in vision.

**Comment by oleg-jukovec** [comment]
Let's summarize my ideas for now:

https://github.com/tarantool/go-tarantool/issues/7
https://github.com/tarantool/go-tarantool/issues/129
https://github.com/tarantool/go-tarantool/issues/136
https://github.com/tarantool/go-tarantool/issues/211
https://github.com/tarantool/go-tarantool/issues/235
https://github.com/tarantool/go-tarantool/issues/236
https://github.com/tarantool/go-tarantool/issues/237
https://github.com/tarantool/go-tarantool/issues/238
https://github.com/tarantool/go-tarantool/issues/239
https://github.com/tarantool/go-tarantool/issues/240
https://github.com/tarantool/go-tarantool/issues/241

There are no critical changes in the interface here. Some incompatibilities are expected, but it seems like nothing critical.
