### ISSUE TITLE
Reconnection strategy - round-robin between instances

### ISSUE THREAD

**Issue by sharonovd** [tarantool/go-tarantool#68]
Use-case: tarantool is deployed as a geo-distributed cluster, and when one DC goes down, application must switch to reserve DC with minimal service disruption.

Proposal 1: add built-in reconnect strategy which would take several connection URI's as a config, and would quickly to establish connection to them in a circle, returning the first succesful one.
Edge-case: if all URIs are unavailable, return error.

Proposal 2: implement overridable connection strategy class (as in tarantool-java), and provide proposal 1 as example.

**Comment by funny-falcon** [comment]
imho, it will be better to add it as subpackage by managing several tarantool.Connection.

BTW, which way it should determine new master? Or is your setup multimaster cluster?

**Comment by sharonovd** [comment]
I did not get you proposal at full extent - but it seems viable as well.

Regarding your question - yes, such failover strategy works on multimaster setup (e. g. active-hot standby)

**Comment by sharonovd** [comment]
Done in #71
