### ISSUE TITLE
Is Tarantool 2 supported?

### ISSUE THREAD

**Issue by snaffi** [tarantool/go-tarantool#70]

**Comment by Totktonada** [comment]
@funny-falcon The protocol is described [here][1]. One can use tarantool-c connector [code][2] as example.

[1]: https://tarantool.io/en/doc/2.1/dev_guide/internals/sql_protocol/
[2]: https://github.com/tarantool/tarantool-c/blob/master/tnt/tnt_execute.c

**Comment by funny-falcon** [comment]
Ok, will do that soon.

**Comment by Totktonada** [comment]
Looks as duplicate of #62. I would close this issue.

**Comment by Totktonada** [comment]
Closing as duplicate of #62.
