### ISSUE TITLE
Returned error for request without permissions

### ISSUE THREAD

**Issue by buff0** [tarantool/go-tarantool#75]
When I make a request to the space for which I do not have permission, an error is returned ```there is no space with name _```, however i would like to get something like```permission denied```

**Comment by funny-falcon** [comment]
I'll look at, but doubtfully it could be fixed on connector side. I think, that is what tarantool sends back. 

What you get when you try to do it through `net.box` in lua console?

**Comment by kostja** [comment]
Whatever tarantool sends back, it does not distinguish between existing and non-existing spaces. There is no way to find out whether a space exists or not if you don't have access to it - the opposite would be a security vulnerability.

**Comment by buff0** [comment]
Thanks.
