### ISSUE TITLE
Insert a filled structure by prototype.

### ISSUE THREAD

**Issue by sttyru** [tarantool/go-tarantool#82]
Would it be too much trouble for you have a share an example of insert (and upsert) of a filled struct instead a separate interfaces? My procedure of data insertion (upsert) have a look like:
```
r, err := cnf.Tptr.Upsert("hosts", []interface{}{vhostname,cpuq}, []interface{}{[]interface{}{"=", 1, cpuq})
```
Can I replace that by a more abstract, where 'StructOne' is a prototype of a tuple and 'StructTwo' is a filled structure? E.g. (it isn't correct and used for mine idea):
```
r, err := cnf.Tptr.Upsert("hosts", []interface{}{StructOne}, []interface{}{[]interface{}{"=", *StructOne})
```

**Comment by funny-falcon** [comment]
```
r, err := cnf.Tptr.Upsert("hosts", StructOne, []interface{}{[]interface{}{"=", 1, cpuq})
```
StructOne should implement EncodeMsgpack (or have a field ``_msgpack struct{} `msgpack:",asArray"` ``).
Condition is better to be written that way.

**Comment by sttyru** [comment]
I got. Thank you! :)
