### ISSUE TITLE
Store a rawhide JSON (or binary?)

### ISSUE THREAD

**Issue by sttyru** [tarantool/go-tarantool#83]
Hello!

Can I store in Tarantool a rawhide JSON data or a data in binary format?
I want to store in a box a 'history' of remote-application replies in JSON-format for future re-use (e.g. in cases when an 3rd application require a full reply: key, values and JSON's structure)
 If I try to convert an incoming data to string (with 'Sprintf') and try to put them in tuple as 'string' result of an operation has been failed (stored only a part of string). Should I prepare a data with some special tricks or can I store a data in a binary? I know than storing of an rawhide' JSON is not a better idea and I know about hazards & adventures in a future :)

Thank you.

**Comment by kostja** [comment]
Github issue is not appropriate place for a support question. Please use a mailing list or Tarantool telegram channel. Yes you can.

**Comment by sttyru** [comment]
Ok. I got it.
