### ISSUE TITLE
Expose Future.wait() and Future.err as part of public API

### ISSUE THREAD

**Issue by bm0** [tarantool/go-tarantool#86]
Hi guys!
We try implement replicaset using this connector.
Replicaset in our understanding is thing that collect multiple connections and can do retry query when one of connection timed out or unavailable.

There is a problem. We make *Async() queries in loop over connection, after we can't understand whether to retry because for this we need to do two things:
1. Wait for Future will filled.
2. Check that Future.err equals nil. If it is not, try again on next connection.

```go
for i, conn := range connections {
	futCh := make(chan *tarantool.Future, 1)
	errCh := make(chan error, 1)
	ctx, cancel := context.WithTimeout(context.Background(), queryTimeout)

	go func() {
		fut := query(conn)
		fut.wait()
		if fut.err != nil {
			errCh <- fut.err
			return
		}
		
                futCh <- fut
	}()

	select {
	case <-ctx.Done():
		cancel()
		continue
	case fut := <-futCh:
		cancel()
		return fut, nil
	case err := <-errCh:
		cancel()
		return nil, err
		}
	}
}
```

**Comment by bm0** [comment]
I would like to discuss with you the possibility of adding such functionality and its design. I will be glad to contribute to your project.

**Comment by funny-falcon** [comment]
Probably I read it wrong, but I don't understand at the moment, why Future.Get() doesn't satisfy you.

**Comment by funny-falcon** [comment]
I pushed commit that exposes WaitChan() and Err().
