### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by k0st1an** [tarantool/go-tarantool#88]
I have an extremely simple program for testing WPS (in this case, 30k). But at the same time I have a memory leak. How can this be fixed?

```go
import uuid "github.com/satori/go.uuid"

func init() {
...
opts := tarantool.Opts{User: conf.User}
	conn, err = tarantool.Connect(conf.URI, opts)
	if err != nil {
		log.Fatalln("Connection refused:", err)
	}
...
}

func main() {
...
	go writeProcess()
...
}

func writeProcess() {
	writeLimiter := rate.NewLimiter(rate.Limit(conf.WPS), 100)
	for {
		go write()
		sleep(writeLimiter)
	}
}

func write() {
	id := uuid.NewV4().String()

	_, err := conn.Insert(conf.Space, []interface{}{id, time.Now().UTC().Unix(), conf.FakeDataStr})
	if err != nil {
		log.Fatalln("Error:", err)
	}
...
}
```
![image](https://user-images.githubusercontent.com/426513/73847391-3d799200-4837-11ea-934d-0adb73066e55.png)
![image](https://user-images.githubusercontent.com/426513/73847396-410d1900-4837-11ea-84f7-6ed2be0a9746.png)

**Comment by funny-falcon** [comment]
Can you give compilable single-file reproduce code? It will greatly improve my ability to identify an issue.

With profile picture I could suppose you insert 10MB strings and/or insert much faster than tarantool could write them, therefore they are in in-flight requests buffer. Probably I misinterpret it.

This connector is certainly in production usage of many users, and such thing as memory leak should have been found much earlier.

**Comment by k0st1an** [comment]
> 10MB

640 bytes

You're right. I set the timeout and immediately saw a lot of unfinished inserts.
