### ISSUE TITLE
Connect to unix socket

### ISSUE THREAD

**Issue by swood** [tarantool/go-tarantool#89]
Hi everyone.

I try to connect to the UNIX socket with the next code:
```
	server := "unix:///local/tarantool/var/tarantool.sock"
	opts := tarantool.Opts{
		Timeout: 500 * time.Millisecond,
	}
	client, err := tarantool.Connect(server, opts)
	if err != nil {
		log.Fatalf("Failed to connect: %s", err.Error())
	}
```

I got message:
```
2020/02/26 18:28:50 Failed to connect: Wrong reponse header
```

Probably someone could get me a clue about the cause of this answer?

**Comment by FizikRoot** [comment]
The same problem 
but if you add client and password parameters
`2020/08/28 16:33:07 Failed to connect: client connection is not ready (0x4000)`

if I add to configuration Concurrency, then I get the error
`2020/08/28 15:47:05 tarantool: reconnect (0/2) to unix:///var/run/tarantool/test.router-1.control failed: auth: scrambling failure illegal base64 data at input byte 4`

**Comment by 0x501D** [comment]
Cannot reproduce it, need more data: versions of tarantool and go-tarantool.

**Comment by 0x501D** [comment]
We can get error:" Connection refused: Wrong reponse header" if tarantool setup is incorrect:
This is wrong:
```
console = require('console')
console.listen('unix/:/tmp/tnt')
```
This is correct setup:
```
box.cfg{
    listen = 'unix/:/tmp/tnt'
}
```

**Comment by Totktonada** [comment]
It seems, the problem is that the connector goes to a console socket instead of the binary protocol socket. Everything should work with the socket file that is configured in `box.cfg{listen = <...>}`.

If it is not your case, feel free to reopen with full reproducer: lua file, go code, recipe how to run.
