### ISSUE TITLE
Can't insert digits >= 128

### ISSUE THREAD

**Issue by nizsheanez** [tarantool/go-tarantool#9]
Test case:
```
package main

import (
	"fmt"
	"github.com/tarantool/go-tarantool"
)

func main() {
	spaceNo := uint32(512)
	indexNo := uint32(0)

	client, err := tarantool.Connect("192.168.99.100:3301", tarantool.Opts{
		User: "test",
		Pass: "test",
	})
	if err != nil {
		panic(err)
	}

	cases := map[string]interface{}{
		"uint64": uint64(128),
		"uint32": uint32(128),
		"uint": uint(128),
		"int64": int64(128),
		"int32": int32(128),
		"int": int(128),
	}
	for caseName, val := range cases {
		v := []interface{}{val}
		_, err = client.Insert(spaceNo, v)
		if err != nil {
			fmt.Printf("%s: %s\n", caseName, err.Error())
		} else {
			fmt.Printf("%s: Success\n", caseName)
		}
		client.Delete(spaceNo, indexNo, v)
	}
}
```
Output:
```
uint64: Success
uint32: Success
uint: Success
int64: Tuple field 1 type does not match one required by operation: expected NUM (0x8017)
int32: Tuple field 1 type does not match one required by operation: expected NUM (0x8017)
int: Tuple field 1 type does not match one required by operation: expected NUM (0x8017)```
```

It's msgpack behaviour, it pack small signed int to smallest possible int and tarantool recieve negative value

It's not a problem to use unsigned ints, just all tests in `tarantool_test.go` using signed

**Comment by mialinx** [comment]
Problem seems to be tricky.

Go and C msgpack libraries pack signed int in different ways.
https://gist.github.com/mialinx/eaaa22c50de73c257770

So, problem may be in Go msgpack.
We dealing with it...

**Comment by mialinx** [comment]
#1241 - ticket on server for supporting suboptimaly encoded ints.
docs and tests were fixed as temporary workaround

**Comment by mialinx** [comment]
Msgpack implementation was fixed https://github.com/vmihailenco/msgpack/issues/61

Unfortunately, there is no way to specify exact dependency version in pure go, 
so just update msgpack and rebuild your project
