### ISSUE TITLE
Is there support of built-in UUID type?

### ISSUE THREAD

**Issue by pashinin** [tarantool/go-tarantool#90]
How can I insert uuid field from Golang?

**Comment by funny-falcon** [comment]
Do you mean https://github.com/tarantool/tarantool/commit/d68fc29246714eee505bc9bbcd84a02de17972c5 ?

Certainly one could introduce such type by hands with such ext encoding.

I'll think about soon.

**Comment by pashinin** [comment]
Yes

` and it is now
possible to insert UUIDs into spaces, but only into unindexed fields`

and I wanted to insert into an indexed UUID field

**Comment by Totktonada** [comment]
[2.4.0-182-gd68fc2924](https://github.com/tarantool/tarantool/commit/d68fc29246714eee505bc9bbcd84a02de17972c5) allows to insert an UUID value into an unindexed field, but [2.4.0-183-gb238def80](https://github.com/tarantool/tarantool/commit/b238def8065d20070dcdc50b54c2536f1de4c7c7) enables support of indexing of such values.

**Comment by pashinin** [comment]
@Totktonada fine. I do not understand what to pass to "insert".

Example:

```
// insert new tuple { 10, 1 }
resp, err = client.Insert(spaceNo, []interface{}{uint(10), 1})
// or
resp, err = client.Insert("test", []interface{}{uint(10), 1})
```

How to insert UUID:

```
resp, err = client.Insert("test", []interface{}{?????-????-????-??????, 1})
```

I tried:

```
"github.com/satori/go.uuid"

uuid.NewV4().String(),
// uuid.NewV4().Bytes(),
// uuid.NewV4(),
```

**Comment by funny-falcon** [comment]
Type should be registered in messagepack library.
See "Old way to to register types": https://github.com/tarantool/go-tarantool#custom-unpacking-and-typed-selects-and-function-calls

**Comment by pashinin** [comment]
You better know in what format it should be. Look at this please:

First I wirte MP_EXT, then MP_UUID and then bytes of UUID but something is wrong.

```
func encodeUUID(e *msgpack.Encoder, v reflect.Value) error {
	m := v.Interface().(uuid.UUID)
	// MP_EXT = 10
	if err := e.EncodeUint8(10); err != nil {
		return err
	}

	// MP_UUID = 2
	if err := e.EncodeUint8(2); err != nil {
		return err
	}

	if err := e.EncodeBytes(m.Bytes()); err != nil {
		return err
	}

	return nil
}
```

Have this error now:

`Invalid MsgPack - packet body (0x14)`

**Comment by eaglemoor** [comment]
Why u can't use uuid as string ?

**Comment by funny-falcon** [comment]
Sorry, but I don't understand your code. It doesn't coherent with[ messagepack specification](https://github.com/msgpack/msgpack/blob/master/spec.md)
 
It seems vmihailenko's msgpack defines special way to register EXT types:
https://github.com/vmihailenco/msgpack/blob/v2.9.1/ext.go#L26 
And then define encoder with format like https://github.com/tarantool/tarantool/blob/master/src/lib/uuid/mp_uuid.c#L42-L74

**Comment by funny-falcon** [comment]
But looks like it still will be decoded in a strange way in a generic result:
https://github.com/vmihailenco/msgpack/blob/v2.9.1/ext_test.go#L112

**Comment by AmsTaFFix** [comment]
hi all, we found a way to send uuid to tarantool with vmihailenco/msgpack.v2

@pashinin 
Your example will not work because of method `EncodeBytes` will always add len of array first, so you get additional `2 bytes + 16 bytes` and it's `invalid msgpack`.

There is no way to encode proper uuid with `msgpack.CustomEncoder`/`msgpack.CustomDecoder`, because you have only `msgpack.Encoder`, which can't just write exactly 16 bytes. To accomplish proper marshaling, we have to you use deprecated interfaces `msgpack.Marshaler`/`msgpack.Unmarshaler`

Here is a way
**app.lua**
```
box.cfg({
    listen = 3301,
    memtx_memory=128 * 1024 * 1024,
    read_only=false,
    log_level=2,
    log_format='json',
})

box.once('bootstrap', function()
    box.schema.user.create('test_user', { password = 'test_password' })
    box.schema.user.grant('test_user', 'read,write,execute', 'universe')
end)

uuid = require("uuid")
log = require("log")
api = {}
api.test = function(id)
    log.error("is uuid " .. tostring(uuid.is_uuid(id)))
    log.error("type is " .. type(id))
    log.error("id is " .. id:str())

    return id
end
```

**main.go**
```
package main

import (
	"fmt"
	"github.com/google/uuid"
	"github.com/tarantool/go-tarantool"
	"gopkg.in/vmihailenco/msgpack.v2"
	"log"
)

// have to create wrapping structure, because it's only way to add marshal/unmarshal 
// methods, which can just write N bytes
type UUIDMarshaler struct {
	uuid.UUID
}

// add function to marshal/unmarshal for custom struct

func (id UUIDMarshaler) MarshalMsgpack() ([]byte, error) {
	b, err := id.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("can't marshal uuid: %w", err)
	}
	return b, nil
}

func (id *UUIDMarshaler) UnmarshalMsgpack(b []byte) error {
	if len(b) != 16 {
		return fmt.Errorf("invalid data length: got %d, wanted 16", len(b))
	}
	UUID, err := uuid.FromBytes(b)
	if err != nil {
		return fmt.Errorf("error converting bytes to uuid: %w", err)
	}
	id.UUID = UUID
	return nil
}

// register extension on init
func init() {
	msgpack.RegisterExt(2, (*UUIDMarshaler)(nil))
}

func main() {
	tntClient, err := tarantool.Connect(
            "localhost:3301", 
            tarantool.Opts{User: "test_user", Pass: "test_password",})
	if err != nil {
		log.Fatalf("can't connect to tarantool: %s", err)
	}

	id := uuid.New()
	log.Printf("uuid as string is '%s'", id.String())

        // wrap id to marshal properly
        resp, err := tntClient.Call17("api.test", []interface{}{UUIDMarshaler{id}})
	if err != nil {
		log.Fatalf("can't call api.test: %s", err)
	}

	idFromTnt := (resp.Data[0]).(UUIDMarshaler).UUID
	log.Printf("id returned from tnt as string is '%s'", idFromTnt)
}
```

**Comment by Maximilan4** [comment]
@AmsTaFFix I have a problem with your decoder example, when trying to decode map to struct. Then I have two additional fixed bytes too, as you described above.  I add this before `uuid.FromBytes(bytes)`:
```
if bytes.Equal(buffer[:2], []byte{0xd8, 0x2}) {
    twoMore := make([]byte, 2)
    _, err = d.Buffered().Read(twoMore)

    if err != nil {
	return err
    }
    bytes = append(bytes, twoMore...)
    bytes = bytes[2:]
}
```

**Comment by AmsTaFFix** [comment]
> @AmsTaFFix I have a problem with your decoder example, when trying to decode map to struct. Then I have two additional fixed bytes too, as you described above. I add this before `uuid.FromBytes(bytes)`:
> 
> ```
> if bytes.Equal(buffer[:2], []byte{0xd8, 0x2}) {
>     twoMore := make([]byte, 2)
>     _, err = d.Buffered().Read(twoMore)
> 
>     if err != nil {
> 	return err
>     }
>     bytes = append(bytes, twoMore...)
>     bytes = bytes[2:]
> }
> ```

thank you, i fixed my example
