### ISSUE TITLE
Lost example for Go connector

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/go-tarantool#92]
Section readme [hello world](https://github.com/tarantool/go-tarantool#hello-world) sends us to the documentation with an example.

But the [doc](https://www.tarantool.io/en/doc/2.3/book/connectors/#go) page contains nothing but a link to the original repository.

**Comment by Totktonada** [comment]
It was filed as https://github.com/tarantool/doc/issues/1429 against tarantool documentation.
