### ISSUE TITLE
Adding if_not_exists as parameter for calling box.schema.space.create causes an error unsupported Lua type 'function' (0x20)

### ISSUE THREAD

**Issue by kokizzu** [tarantool/go-tarantool#94]
Normally without parameter:
```
res, err := conn.Call(`box.schema.space.create`, AX{`test`})
// no error
// or error 0xa Space already exists when called twice
```
With `if_not_exists` parameter:
```
res, err := conn.Call(`box.schema.space.create`, AX{`test`, map[string]interface{}{`engine`:`vinyl`,`if_not_exists`:true}})\
// error: unsupported Lua type 'function' (0x20)
```
Note:
```
type AX []interface{}
```

**Comment by kokizzu** [comment]
same thing happened with `box.schema.create_space`

**Comment by filonenko-mikhail** [comment]
Try to use small trick on Tarantool Lua side:

```lua
require('msgpack').cfg{encode_invalid_as_nil = true}
```

**Comment by kokizzu** [comment]
is there no client side solution for this?

**Comment by funny-falcon** [comment]
https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_schema/space_create/

> Return type:
> userdata

userdata could not be encoded to msgpack.
No, there is no client side solution. (Perhaps, except Eval with explicit `return true` at the end.)
You'd better wrap box.schema.space.create into your own function which returns `true` (for example).

**Comment by Totktonada** [comment]
There is nothing we can do on the client side (except `Eval` if permissions on the server allows). Consider workarounds above.
