### ISSUE TITLE
(*smallWBuf).Write holds memory

### ISSUE THREAD

**Issue by SergeiHaidukov** [tarantool/go-tarantool#95]
Hello !
I call a function in tarantool and pass ~10MB []map[string]interface{}. After that, memory is allocated on the heap, but it is not released after the procedure is executed. What can be done about it ?

 Showing top 10 nodes out of 62

      flat  flat%   sum%        cum   cum%
    0.78GB 43.04% 43.04%     0.78GB 43.04%  github.com/tarantool/go-tarantool.(*smallWBuf).Write
    0.63GB 34.80% 77.84%     0.63GB 34.80%  github.com/tarantool/go-tarantool.(*smallWBuf).WriteString
    0.11GB  5.78% 83.62%     0.19GB 10.43%  gopkg.in/vmihailenco/msgpack%2ev2.decodeMap
    0.10GB  5.68% 89.30%     0.10GB  5.68%  github.com/tarantool/go-tarantool.(*smallWBuf).WriteByte
    0.05GB  2.87% 92.16%     0.05GB  2.87%  github.com/json-iterator/go.(*Stream).Write

**Comment by funny-falcon** [comment]
Yes. I reuse write buffer, and didn't bother with eventual dropping it out.
In other connectors I drop buffer once in 1000 calls. Should I do it here as well?
You can decrease impact by setting Concurrency to lower value, I suppose. Try to set it to 1.

(btw, 10MB data in a single call is not too good for single core tarantool. But probably it is not issue for you)

**Comment by SergeiHaidukov** [comment]
Thanks for the answer!
With Concurrency:1 consumes less memory. I suppose it makes sense to drop the buffer.
Can make this behavior configurable. Specify the number of calls.

**Comment by funny-falcon** [comment]
Try latest version, please
